TESTS WITH ERRORS 
test13_BFS_Hanoi_02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 52, in runPlayXSteps
    results = self.pool.apply_async(self.playXSteps, [solver, plays]).get(timeout)
  File "C:\Program Files\Python37\lib\multiprocessing\pool.py", line 679, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 296, in test13_BFS_Hanoi_02
    [23, ((5,), (4,), (1, 2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 57, in runPlayXSteps
    raise Exception("Timed out: %s" % inspect.stack()[1][3])
Exception: Timed out: test13_BFS_Hanoi_02

-------------------------------
TESTS FAILED  
test04_GM_Hanoi_04 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 124, in test04_GM_Hanoi_04
    self.assertEqual(th.getGameState(), ((1,3,4,5),(),(2,)))
AssertionError: Tuples differ: ((1, 3, 4, 5), (), (1, 2)) != ((1, 3, 4, 5), (), (2,))

First differing element 2:
(1, 2)
(2,)

- ((1, 3, 4, 5), (), (1, 2))
?                     ^ --

+ ((1, 3, 4, 5), (), (2,))
?                     ^


test08_GM_8Puzzle_04 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 200, in test08_GM_8Puzzle_04
    self.assertEqual(p8.getGameState(), ((1,-1,3,),(8,2,4),(7,6,5)))
AssertionError: Tuples differ: ((1, 2, 3), (8, -1, 4), (7, 6, 5)) != ((1, -1, 3), (8, 2, 4), (7, 6, 5))

First differing element 0:
(1, 2, 3)
(1, -1, 3)

- ((1, 2, 3), (8, -1, 4), (7, 6, 5))
?      ^          ^^

+ ((1, -1, 3), (8, 2, 4), (7, 6, 5))
?      ^^          ^


test14_BFS_Hanoi_03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 314, in test14_BFS_Hanoi_03
    [23, ((1, 4, 5), (), (2, 3))],
  File "C:\Users\kille\academics\automatedgradingapp\app\testing\uninformed-solvers\gradingtests.py", line 55, in runPlayXSteps
    self.assertEqual(results[index], expected)
AssertionError: Tuples differ: ((2,), (1, 3, 4, 5), (1, 2)) != ((3, 4, 5), (1, 2), ())

First differing element 0:
(2,)
(3, 4, 5)

- ((2,), (1, 3, 4, 5), (1, 2))
+ ((3, 4, 5), (1, 2), ())

-------------------------------
TESTS SKIPPED 
-------------------------------
